Environment vars
sleighzy/ansible-zookeeper pull request #2
Opened 2018-10-31 17:51 UTC by nerdynick

This moves the Env Vars from the System.d service script and into a defaults file. As well as adds support for including arbitrary Env Vars. 

Use case for this change was to support setting the JVMFLAGS var for Zookeeper start scripts as well as support for GC and other tunings if needed.

2018-11-05 05:47 UTC, sleighzy requested changes
@nerdynick , thanks for the PR. Can you update the README.md file to include a reference to this new configuration file for those environment variables as well please.

2018-11-05 19:39 UTC, nerdynick commented
README is now updated to show an example

2018-11-05 23:19 UTC, sleighzy commented
Apologies, I should have been more explicit. Can you add a line item to the the list of files in the "Default Directories and Files" to reflect the new /etc/default/zookeeper file that is created and included as an EnvironmentFile.

2018-11-05 23:28 UTC, nerdynick commented
Ah, sorry about that. Should be added now. Also added table header for the Desc column

2018-11-06 07:01 UTC, sleighzy commented on templates/default.j2
> +{% for key, value in zookeeper_environment.iteritems() %}
Having looked at the below document it looks like ```iteritems()``` isn't supported by Python 3. ```dict.items()``` should be used instead to be compatible with both Python 2 and 3:

https://docs.ansible.com/ansible/2.5/user_guide/playbooks_python_version.html

2018-11-06 17:29 UTC, nerdynick commented
That Python3 change is done

2018-11-07 04:27 UTC, merged

2018-11-07 04:28 UTC, sleighzy commented
Thanks. Much appreciated.

2018-11-07 04:48 UTC, sleighzy reviewed
Passed Travis CI build. All good.