Allow optional variable to use inventory_hostname instead of ansible_hostname
sleighzy/ansible-zookeeper pull request #38
Opened 2022-07-25 01:47 UTC by ObjectiveTruth

This PR includes a README to explain the issue that I encountered with this role. 

I've dded an optional parameter(that defaults to false to preserve current behaviour) where the hostname used in the server list is used. This happens when the the host only gives its hostname instead of its FQDN(Fully Qualified Domain Name). This can cause the server being unable to see each other. 

Also, this could be required if you want/need to use TLS since the hostname needs to match the certificate it presents

2022-07-25 01:48 UTC, ObjectiveTruth commented
Partially addresses #27

2022-07-25 13:04 UTC, ObjectiveTruth commented
Fixed up the README linting issues reported using force push

2022-07-26 13:00 UTC, ObjectiveTruth commented
I enabled the linter on my fork, so the new forced push updates should pass all the tests this time 👍

2022-07-27 11:42 UTC, ObjectiveTruth commented
Can this be merged, @sleighzy?

2022-07-28 07:02 UTC, sleighzy requested changes

2022-07-28 07:02 UTC, sleighzy commented on README.md
> +    - role: edgefotwaresolutions.zookeeper
Change the role name:

```suggestion
    - role: sleighzy.zookeeper
```

2022-07-28 07:02 UTC, sleighzy commented on defaults/main.yaml
> +zookeeper_use_servers_inventory_hostname: false
Could you please rearrange the variable name slightly, means it will align better with the existing `zookeeper_servers` variable.

```suggestion
zookeeper_servers_use_inventory_hostname: false
```

2022-07-28 07:02 UTC, sleighzy commented on README.md
> +Assuming the following inventory file and assuming the hostname command for
Can you please rephrase this slightly:

```suggestion
Assuming the below inventory file, and that the `hostname` command returns only the hostname and does not include the domain name.
```

2022-07-28 07:02 UTC, sleighzy commented on README.md
> +The `zoo.cfg` will template the following(Assuming all other defaults)
Can you please rephrase this slightly:

```suggestion
The templated `zoo.cfg` file will contain the below entries:
```

2022-07-28 07:04 UTC, sleighzy commented
> Can this be merged, @sleighzy?

Hi @ObjectiveTruth . I've dropped a couple of comments on this now, and a request for slightly renaming the variables. I'll merge it in once you push the changes.

Thanks heaps by the way, much appreciated for the efforts and updates. Will be very helpful given this problem has come up before.

2022-07-28 19:23 UTC, sleighzy requested changes

2022-07-28 19:23 UTC, sleighzy commented on defaults/main.yaml
> +zookeeper_use_servers_inventory_hostname: false
@ObjectiveTruth , this variable still needs to be updated.

2022-07-29 11:30 UTC, ObjectiveTruth commented on README.md
> +    - role: edgefotwaresolutions.zookeeper
Applied

2022-07-29 11:32 UTC, ObjectiveTruth commented
I've applied the updates and you're right the tests were failing because I missed the variable name change in the `defaults/main.yml` should be good to merge now

2022-07-30 00:29 UTC, sleighzy approved these changes

2022-07-30 00:30 UTC, merged

2022-07-30 00:31 UTC, sleighzy commented
Thanks @ObjectiveTruth , all sorted now, cheers for the contribution.

2022-07-31 01:54 UTC, ObjectiveTruth commented
> Thanks @ObjectiveTruth , all sorted now, cheers for the contribution.

No problem! Glad i could help 👍